src/utils/bindings.ts

In order to avoid confusion between `powershell` and `pwsh` on MacOS/Linux, remove it as a binding option on those OS's
Closes #18

fix: only show 'powershell' binding on windows

---

src/ui/ui-bind.tsx
src/utils/bindings.ts

Load the profile dynamically from pwsh/powershell in order to support OneDrive based `$profile`'s. 
Closes #4

fix: use active profile for pwsh/powershell to support one drive directories

---

README.md

As is tested in the CI, `inshellisense` currently will support node >= 16.x
Closes #24 & closes #14

docs: update readme to include supported node versions

---

src/utils/bindings.ts

Fixes that invoking `powershell` or `pwsh` to check the profile could fail due to the shell not being installed on the system.
Closes #28

fix: failing config extraction for powershell in MacOS/Linux

---

src/commands/root.ts
src/ui/ui-init.tsx

The current error log when executed without arguments may be confusing to new users. This PR implements the ability to select a shell using the cursor when executed with no args.
Thank you for your consideration.

feat: ask for desired shell if no args

---

src/commands/root.ts
src/index.ts
src/utils/shell.ts

Adds the above described fixes after changes from #91

fix: shell inference when ENV:SHELL isn't set & add back option for user to supply shell

---

src/isterm/pty.ts
src/ui/suggestionManager.ts
src/ui/ui-root.ts
src/ui/utils.ts
src/utils/ansi.ts

Does the following:
- Adds back suggestion descriptions 
- Adds in argument descriptions
- Fixes issue with noops for rendering changes on key navigation
- changes `^space` to `>` for sending tab when suggestions are active.

feat: restore argument descriptions & tweak keystroke management

---

README.md

This pull request addresses a minor typo in the README.md file where  the Node-gyp package link leads to a 404 error page, and this fix updates it to the correct repository URL. 
here's screenshot of the page that the current link redirect too :

 docs: fix typo in Node-gyp Package Repository Link in README.md file

---

src/isterm/commandManager.ts

Accepting something like `git co` -> `git commit ` fails to register the last space so options like `-m` never appear.

fix: completion fails to detect space when represented with cursor movement

---

src/commands/root.ts
src/index.ts
src/isterm/pty.ts
src/ui/ui-root.ts

The user can check if they are in an `inshellisense` session via `is -c` and it prevents running nested sessions.

feat: ability to check if the terminal in an `inshellisense` session

---

src/runtime/generator.ts
src/runtime/utils.ts

Fixes the failure of a generator when the script is provided as a javascript array of arguments. Additionally logs the failure for easier debugging.
Closes #48

fix: generator when script is provided as array

---

src/runtime/utils.ts

Powershell will fail on `cd ` because the child process throws an async error uncaught in the event loop. This captures and logs the error

fix: uncaught errors when shell script generator fails

---

shell/shellIntegration-rc.zsh

fix: typo triggering VSC instead of IS escape function

---

package-lock.json
package.json

#148
I currently believe that we need to lock the autocomplete version until loadspecs is compatible.

fix: lock autocomplete version

---

README.md
package.json

`node-pty` only currently supports node 18, but will still work for now with Node 16/Node 20. Including node versions as part of the readme.  Closes #144

docs: update to reflect node versions

---

.github/workflows/ci.yml
jest.config.cjs
shell/shellIntegration-rc.zsh
shell/shellIntegration.bash
shell/shellIntegration.fish
shell/shellIntegration.ps1
src/commands/root.ts
src/index.ts
src/isterm/pty.ts
src/tests/isterm/pty.test.ts
src/tests/runtime/__snapshots__/runtime.test.ts.snap
src/tests/runtime/runtime.test.ts
src/ui/ui-root.ts

Instead of respecting the user's prompt, force an empty prompt of `> ` or `PS >` to hide user information and make testing less flaky / support testing snapshots.

feat: add hidden flag for forcing default inshellisense prompt for testing

---

.husky/pre-commit
package-lock.json
package.json

Ensure that the commit code automatically lint to avoid style issues.
@cpendery  thanks.

build: add husky,support lint code when pre-commmit

---

src/ui/suggestionManager.ts

I realized that the reset index logic I did before wasn't rigorous, so I adjusted the reset position.
The index should be reset when the complement is empty or when the complement is recalculated to get a value.
@cpendery thanks.

fix: reset index after getSuggestions

---

src/runtime/runtime.ts

First of all, thanks for this awesome project, which has given me a lot of inspiration in the areas of terminal experience and smart completion. I have recently been trying to integrate it with Xterm.js. However, I encountered some issues while using it and reading the code.
When I type `npm run`, the terminal autocomplete returns the incorrect result "--registry", instead of the scripts in package.json or other run parameters. 
This behavior is somewhat strange, so I delved into the source code to look for the issue.
After spending some time debugging, the problem was finally located in the `genSubCommand` method of the `runtime.ts` file.
Here, we can see that when typing `npm run`, function `genSubCommand` attempting to find `s.name === 'run' `within ·parentCommand.subcommands· is …

fix: subCommands find problem

---

src/ui/suggestionManager.ts
src/ui/ui-root.ts

When executing a command with live suggestions `git `, the suggestions were appearing after command execution due to a race condition. This fixes that by applying a manual check after the promise is resolved that the suggestion should still be provided

fix: stale suggestion appearing after command execution

---

.github/workflows/ci.yml
.gitignore
package-lock.json
package.json
shell/shellIntegration-rc.zsh
src/isterm/pty.ts
src/tests/ui/autocomplete.test.ts
src/tests/ui/status.test.ts
tui-test.config.ts

Adding detailed e2e tests using [tui-test](https://github.com/microsoft/tui-test) which I made for this purpose. Additionally, this tweaks the zsh shell integration where the user's saved prompt wasn't getting overridden properly when under test. Lastly, this uses a prebuilt node-pty in order to work with shorter install times and on the macOS agents without issues

ci: add detailed e2e tests & prebuilt node-pty

---

shell/shellIntegration-rc.zsh

Closes #174 by adding isterm special characters on the precmd hook instead of just on initial shell init.

fix: zsh integration to work with powerlevel10k / themes

---

README.md
src/commands/root.ts
src/index.ts
src/ui/ui-root.ts

This pull request solves #194 
A new flag is added: `parent-term-exit` which allows users to opt in on closing any parent shells when `is` is started. This is useful for adding is to a `~/.zshrc` configuration.

Update inshellisense commands and options

---

src/isterm/commandManager.ts

Closes #205. Triggered by the active markers nulling during the `vi` alt buffer (expected xterm behavior).

fix: alt buffer issue when entering vi

---

src/commands/root.ts
src/runtime/runtime.ts
src/utils/config.ts

A new configuration option 'specs.path' has been added to allow users to specify a local directory for autocomplete specs. Function loadLocalSpecsSet introduced to load local autocomplete specs from the specified path. The loading of local specs has been integrated into the startup routine.
fixed https://github.com/microsoft/inshellisense/issues/83
@cpendery I realized a version of loading any path, local complementary specification. Do you see OK.
If it's ok, I'll submit the corresponding UT test again. Thanks.

feat: Add support for local autocomplete specs path configuration

---

src/isterm/commandManager.ts

Fixes #208. The issue is that the `@ ` is getting detected as terminating at the `@` so the space becomes part of the command. When calculating if the cursor is at the end of the command, it used `trim` instead of `trimEnd` so the cursor was always found to be 1 character left of the end giving recommendations too early.

fix: prompt terminator replay giving bad suggestions

---

src/isterm/commandManager.ts

Fixes when a command is wrapped to multiple lines when `isWrapped` doesn't detect wrapping for some shells.

fix: suggestions when command wraps terminal

---

src/isterm/commandManager.ts

When clear runs, we could get caught in an infinite loop as no command would be found, limit the search size to the visible terminal buffer.

fix: infinite loop on clear command

---

src/runtime/model.ts
src/runtime/parser.ts
src/runtime/suggestion.ts
src/runtime/utils.ts
src/tests/runtime/__snapshots__/alias.test.ts.snap
src/tests/runtime/__snapshots__/parser.test.ts.snap
src/tests/runtime/__snapshots__/runtime.test.ts.snap
src/tests/runtime/parser.test.ts

Handles cases where escaped spaces or quotes are used in pathname for suggestions in commands like `cd`

fix: support paths containing spaces or quoted paths

---

README.md
src/utils/shell.ts

feat: expand shell plugins to all shells except cmd

---

shell/shellIntegration.bash
src/commands/root.ts
src/index.ts
src/isterm/pty.ts
src/tests/isterm/pty.test.ts
src/ui/ui-root.ts
src/utils/shell.ts

feat: support --login & respect login shells in shell plugins

---

package-lock.json
package.json
src/isterm/pty.ts

Before: 
After: 
Note underlines are hidden due to a bug in vscode, see https://github.com/microsoft/vscode/issues/210326

fix: support more terminal accents & reset accents between different cells

---

src/isterm/commandManager.ts

Approximated clears weren't working on windows pty's since the prompt would get detected twice. Instead, once a clear is detected, it should terminate the `termSync` and wait for the next action to occur.

fix: clears on windows ptys

---

src/ui/suggestionManager.ts

I missed the case in #234 where a suggestion erroneously appears after a user hits enter because of whitespace detected when there was no suggestion at the point of hitting enter. This moves the command clearing above the check for suggestions so that it is always cleared, even if suggestions are visible or not

fix: suggestion appears and hangs after enter

---

src/utils/shell.ts

Fixes the shell setup so bash no longer gets `bash: [: -q: binary operator expected`

fix: bash -q binary operator expected

---

src/commands/specs/list.ts
src/commands/specs/root.ts
src/index.ts
src/runtime/alias.ts
src/runtime/runtime.ts
src/utils/shell.ts

Enhances #154 by supporting local specs & alias specs

feat: add `specs list` command

---

README.md
src/utils/config.ts

Closes #240 by adding support for `~/.config/inshellisense/rc.toml` as a configuration location

fix: add more configuration filepaths

---

src/utils/shell.ts

This improves the shell inference by checking some shell specific environment variables before using the `SHELL` environment variable or the parent process name. Specifically makes `nu` & `xonsh` more reliable on Windows.
Fixes part of #244

feat: improve shell inference

---

src/utils/shell.ts

This fixes a bug in `find-process` where it's trying to use a string method on an undefined object. In this case, we just catch and log the error as debug since this isn't a critical flow (part of the shell detection heuristics)
Closes #270

fix: add try-catch for bug in 'find-process' package

---

shell/shellIntegration-env.zsh
shell/shellIntegration-rc.zsh

Fixes a configuration issue that causes inshellisense to fail when spawning on macOS with zsh
Related to #255 & #261

fix: zsh configs on macos

---

src/commands/root.ts
src/utils/log.ts

As seen in [autocomplete/pre-commit.ts](https://github.com/withfig/autocomplete/blob/master/src/pre-commit.ts), some generators have `console.log` & `console.error`. This PR captures those methods and redirects them to the logfile so those failures aren't bubbled up into the UI
Fixes #280

fix: generators that console log should be captured and redirected to logfile

---

shell/shellIntegration.fish

The current integration printf's the user's prompt function as if it was a format string.
However, as the documentation for fish's printf builtin says:
"       It will also return non-zero if no argument at all was given, in which case it will *print nothing*"
The result is that there are plenty of cases where the printf function will print nothing at all when the prompt function does not return anything.   This is true despite using command substitution to try to get the output as a string.
This is all AFAICT, it's tricky to figure out exactly what happens.
Put another way, this will work fine:
```function fish_prompt; printf (__is_prompt_start); printf %s (is_user_prompt); printf (__is_prompt_end); end```
This will also work fine:
```function fish_prompt; printf (__is_prompt_start); …
```

Fix fish shell integration when prompt function doesn't return anything

---

src/runtime/alias.ts
src/runtime/generator.ts
src/runtime/runtime.ts
src/runtime/utils.ts

There is a constraint with the current [cd spec](https://github.com/withfig/autocomplete/blob/master/src/cd.ts) from fig. It uses `ls -1ApL` to [generate the folder list](https://github.com/withfig/autocomplete-tools/blob/98cd68410a07a78ac805a2de3873ee852e2bda36/generators/src/filepaths.ts#L178-L179), which will fail in pwsh. 
This PR addresses the issue by using Git Bash for generators on Windows. On Linux, having `/bin/sh` as a default will already fix this issue. Users without Git Bash installed will still have issues with cd, but that is an issue at the Fig spec level. I don't want to bring custom specs into inshellisense, so this is the best solution for now.
Closes #12

fix: use git bash for shell commands on windows to reduce generator failures

---

package-lock.json
package.json
src/runtime/alias.ts
src/runtime/parser.ts
src/runtime/runtime.ts
src/runtime/suggestion.ts
src/runtime/utils.ts
src/tests/runtime/__snapshots__/alias.test.ts.snap
src/tests/runtime/__snapshots__/parser.test.ts.snap
src/tests/runtime/alias.test.ts
src/tests/runtime/parser.test.ts
src/utils/shell.ts

Fixes some weird completion issues for paths introduced in #290 along with improving handling quoted & escaped paths for completions across all shells. 
Related to #289

fix: complex paths 

---

.scripts/postinstall.js
README.md
package-lock.json
package.json
src/commands/doctor.ts
src/commands/init.ts
src/index.ts
src/ui/ui-doctor.ts
src/utils/config.ts
src/utils/shell.ts

This PR updates the shell config system so that all the shell configs are now placed under `~/.inshellisense/[shell]/[shell].[ext]`. The init command now only sources those files & they are automatically updated with each install. This will enable updating the configs without requiring user interaction (besides updating their installation) when required (ex. #266). 
It additionally adds a `doctor` command for identifying issues with a user's installation.

feat: update shell config system

---

shell/shellIntegration.fish

It used to be even worse before #288. Fixes #107

fix: shell integration for fish can break prompt layout

---

src/isterm/pty.ts

Fixes #175. The issue of the suggestions not moving the proper width had been fixed in a previous PR. This PR fixes the issue where extra spaces are added into content when clearing the suggestions for wide chars
 
https://github.com/user-attachments/assets/f3b29341-32bc-44a8-be8e-fd68b386a38d
https://github.com/user-attachments/assets/319ef81f-6083-4a6f-86a2-cf866f8a28cf

fix: wide cells on rewrite

---

src/ui/ui-doctor.ts
src/utils/shell.ts

improves the `doctor` command to check to see if the shell plugin exists and is at the end of the file

feat: improve doctor's checking of the shell plugins

---

src/runtime/alias.ts
src/utils/shell.ts

fix: doctor from hanging when checking profile information if plugin is loaded

---

src/utils/shell.ts

As shown in the logs from #322, the doctor command lists warnings for `nu` (it also applies to `pwsh` and `powershell`) right after the plugin is added. There is extra whitespace after those shell commands. This PR removes it and trims the whitespace when comparing the file (which already has a trimEnd() applied)

fix: trailing whitespace after shell plugin causes extra doctor warnings

---

src/runtime/alias.ts

Alias loading can fail on paths with spaces in them on Windows. This PR fixes that by adding quotes around the shell target in the command

fix: alias loading on windows

---

shell/shellIntegration.bash

The ${parameter@P} syntax was first introduced in Bash 4.4, as showed in [bash/CHANGES](https://github.com/bminor/bash/blob/master/CHANGES#L2946). Although the code checks for Bash version >= 4, it does not specify the minor version number. This causes Bash under 4.4 to report an error after each command is executed when using Inshellisense on an older stable platform such as CentOS7.
for example, my bash version is unfortunately v4.2.x, then bash warns every time I type a command and press Enter...
- use bash (4.0 <= version < 4.4)
- the latest Inshellisense
fixing is very simple, The if condition should be more precise, then everything is all right : )

fix: The if condition of __is_report_prompt should be more precise to prevent bash error prompts after each command.

---

src/commands/init.ts

This PR resolves [#335](https://github.com/microsoft/inshellisense/issues/335).
Fixes a bug where the configuration line appended to `.bashrc` by `inshellisense` lacks a trailing newline. This results in broken command concatenation if another tool (e.g., CUDA) appends config lines immediately after.
In `src/commands/init.ts`, added an explicit trailing newline to the `config` output:
```ts
process.stdout.write(`\n\n${config}\n`);
````
Without a newline, tools appending shell config to `.bashrc` (e.g., CUDA) may cause a malformed entry like:
```bash
[ -f ~/.inshellisense/bash/init.sh ] && source ~/.inshellisense/bash/init.shexport PATH=...
```
This breaks shell startup and leads to errors like:
```
bash: /home/user/.inshellisense/bash/init.shexport: No such file or directory
```
* OS: …

fix: add trailing newline in bashrc config to prevent shell errors

---

.github/workflows/ci.yml
README.md
package-lock.json
package.json
shell/shellIntegration.bash
shell/shellIntegration.fish
shell/shellIntegration.nu
shell/shellIntegration.ps1
shell/shellIntegration.xsh
src/isterm/commandManager.ts
src/isterm/pty.ts
src/utils/ansi.ts
src/utils/config.ts
src/utils/shell.ts

This finally fixes the issue where the OSC sequences are pulled out of order and cleans up suggestions randomly getting fired for shells that have full prompt re-writes

feat: use conpty 1.22 for better prompt tracking

---

src/ui/suggestionManager.ts

Related to #337. It's the only issue I could replicate with the sequence
```bash
node -v
clear
node -v
node -v
```

fix: suggestions don't appear after using history to view command after execution

---

src/isterm/pty.ts
src/ui/suggestionManager.ts
src/ui/ui-root.ts
src/ui/utils.ts
src/utils/config.ts

This PR improves the rendering smoothness by re-drawing the cells instead of clearing cells before updating
https://github.com/user-attachments/assets/2bccfdf4-ed2f-4524-9483-02a13fb2bb68
https://github.com/user-attachments/assets/be242e4b-3520-4b30-8922-1e9a998809f0
Closes #278

feat: improve tui smoothness

---

src/runtime/runtime.ts
src/tests/runtime/__snapshots__/runtime.test.ts.snap

fix: empty suggestions block history scrolling

---

src/isterm/commandManager.ts
src/ui/suggestionManager.ts

An issue I was noticing with pwsh as it runs a little slower than git bash with `oh-my-posh`. Suggestions were loading, but not rendering.

fix: don't add command to suggestion cache until suggestions complete loading
