package-lock.json, package.json, src/commands/root.ts, src/isterm/commandManager.ts, src/utils/config.ts
Adds configuration so users can specify their own prompt patterns on windows
=> feat: enable user customized prompt detectors

package-lock.json, package.json, src/isterm/commandManager.ts, src/isterm/pty.ts, src/ui/suggestionManager.ts, src/ui/ui-root.ts
=> fix: suggestions ui to position above rather than forcing screen scroll

src/ui/suggestionManager.ts, src/ui/ui-root.ts, src/utils/ansi.ts
=> fix: cursor movements & escaping suggestions

shell/shellIntegration.bash
Fixes for #101. Related to #79
=> fix: add in missing sourcing for bash's shell integration

src/runtime/runtime.ts, src/tests/runtime/__snapshots__/runtime.test.ts.snap, src/tests/runtime/runtime.test.ts
=> fix: infinite loop when argument is given when spec doesn't have an argument

src/runtime/parser.ts, src/tests/runtime/__snapshots__/parser.test.ts.snap, src/tests/runtime/parser.test.ts
=> fix: command delimiter to support pipelining

src/ui/suggestionManager.ts, src/ui/ui-root.ts
Fixes the error where the description will hang into the user's prompt area if it is larger than the suggestion list. Closes #105
=> fix: description positioning when larger than suggestions card

src/ui/ui-root.ts
When the suggestions render at the bottom of the screen, they were improperly clearing cells on new data, resulting in lots of blank cells where input should be. This fixes that bug
=> fix: improper screen clearing results in blank cells

shell/bash-preexec.sh, shell/shellIntegration-rc.zsh, shell/shellIntegration.bash, shell/shellIntegration.fish, shell/shellIntegration.ps1, src/commands/complete.ts, src/commands/root.ts, src/isterm/pty.ts, src/runtime/generator.ts, src/runtime/runtime.ts, src/runtime/suggestion.ts, src/runtime/template.ts, src/tests/runtime/runtime.test.ts, src/ui/suggestionManager.ts, src/utils/ansi.ts, src/utils/shell.ts
Fixes the cwd value by receiving it from the shell rather than `process.cwd()` which doesn't update as the shell navigates.
Related to #12
=> fix: template & generator's cwd value

package-lock.json, src/commands/complete.ts, src/isterm/pty.ts, src/runtime/generator.ts, src/runtime/parser.ts, src/runtime/runtime.ts, src/runtime/suggestion.ts, src/runtime/template.ts, src/runtime/utils.ts, src/tests/runtime/__snapshots__/runtime.test.ts.snap, src/tests/runtime/runtime.test.ts, src/ui/suggestionManager.ts, src/ui/ui-root.ts
=> fix: generators by syncing types/generators & providing path field support

package.json
=> build: support dev script

src/isterm/commandManager.ts, src/isterm/pty.ts
Fixes the prompt detection when under test and ensure prompts are provided with IS special OSC's
=> fix: cmd prompt controls when under test

src/commands/complete.ts
=> fix: complete command hangs too long upon print

package-lock.json, package.json, src/runtime/generator.ts, src/runtime/suggestion.ts, src/runtime/template.ts, src/tests/runtime/__snapshots__/runtime.test.ts.snap, src/tests/runtime/runtime.test.ts, src/tests/ui/autocomplete.test.ts, src/ui/suggestionManager.ts, src/ui/utils.ts
=> fix: reduce generator failures, add cwd tracking, and improve failure logging

README.md, package-lock.json, package.json, src/isterm/commandManager.ts, src/ui/suggestionManager.ts, src/ui/ui-uninstall.ts, src/utils/config.ts
=> feat: add keybinding support & configuration documentation / tweaks

shell/shellIntegration.bash
=> fix: shell integration with oh-my-bash

shell/shellIntegration.bash
=> fix: PROMPT_COMMAND overriding precmd hook results for oh-my-bash

src/isterm/commandManager.ts, src/tests/utils/ui.test.ts, src/ui/utils.ts
=> fix: bad width calculations when characters are wide

shell/shellIntegration.bash
=> Don't source bash startup files meant for login shells

.github/workflows/ci.yml, package-lock.json, shell/shellIntegration.xsh, src/isterm/pty.ts, src/tests/ui/autocomplete.test.ts, src/utils/shell.ts
=> fix: xonsh should be expected on path, don't search python modules

.github/workflows/ci.yml, shell/shellIntegration.bash, shell/shellIntegration.nu, src/isterm/commandManager.ts, src/isterm/pty.ts, src/runtime/utils.ts, src/tests/ui/autocomplete.test.ts, src/ui/ui-root.ts, src/utils/config.ts, src/utils/shell.ts, tui-test.config.ts
=> feat: add nushell support

src/isterm/pty.ts
=> fix: respect underline, italic, & bold during redraws

src/commands/root.ts, src/runtime/alias.ts, src/runtime/runtime.ts, src/tests/runtime/__snapshots__/alias.test.ts.snap, src/tests/runtime/alias.test.ts
=> feat: add alias expansion for bash & zsh

src/isterm/commandManager.ts, src/isterm/pty.ts, src/ui/suggestionManager.ts
https://github.com/microsoft/inshellisense/assets/35637443/709a42c6-2b15-4af3-a997-0adb78a95340
https://github.com/microsoft/inshellisense/assets/35637443/da019b6a-e73f-4841-995b-a4e61e72c923
=> fix: suggestion hangs after enter

.github/workflows/ci.yml, src/isterm/commandManager.ts, src/isterm/pty.ts, src/utils/config.ts
Closes #245 by adding support for fish
=> feat: support fish on windows

src/ui/suggestionManager.ts
=> fix: hide suggestions during command navigation

src/isterm/commandManager.ts
=> fix: pwsh ghost text detection

shell/shellIntegration-rc.zsh, shell/shellIntegration.bash, shell/shellIntegration.fish, shell/shellIntegration.nu, shell/shellIntegration.ps1, shell/shellIntegration.xsh, src/isterm/commandManager.ts, src/isterm/pty.ts
=> fix: strip osc from prompt detection

.github/workflows/ci.yml, README.md, package-lock.json, package.json
Closes #303, #304, & #307 by adding support for Node LTS
=> build: support node lts

src/utils/shell.ts
=> fix: nit on default safeExec

src/runtime/utils.ts
=> fix: path overlap suggestions

src/runtime/generator.ts
=> fix: filter out null generator output

src/ui/ui-root.ts
Adds improved render clearing with the new smooth renderer #349. This improves performance by only re-rendering patches when suggestions are visible & clearing stale suggestions properly when switching rendering directions (`above -> below` or `below -> above`)
=> fix: improved rendering clearing

src/runtime/runtime.ts, src/utils/config.ts
=> fix: confusing local specs message

src/isterm/commandManager.ts
I think the issue with #328 is they were using a oh-my-posh config with a right prompt, which ends up breaking inshellisense. This PR should fix that issue
=> fix: oh-my-posh right prompt handling

src/runtime/runtime.ts, src/tests/runtime/runtime.test.ts
=> feat: add command suggestions
